version: "3.2"
services:
  app:
    build: .
    ports:
      - "8000:8001"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/database?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    ports:
      - 6432:5432
    expose:
      - 6432
    volumes:
      - db:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  db:
    driver: local